spring.application.name=fitness-backend
spring.datasource.url=jdbc:mysql://localhost:3306/campusfit_db
spring.datasource.username=root
spring.datasource.password=Anusha@30906
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
